server:
  port: 8762

spring:
  cloud:
    azure:
      keyvault:
        secret:
          endpoint: https://js-kv-01.vault.azure.net/
#      credential:
#        client-id: ${eh-sp-client-id}
#        client-secret: ${eh-sp-secret}
#      profile:
#        tenantId: ${eh-tenant-id}
    function:
      definition: consume;supply
    stream:
      kafka:
        binder:
          brokers: js-cluster-01.servicebus.windows.net:9093
      bindings:
        consume-in-0:
          destination: demo-topic
          group: $Default
        supply-out-0:
          destination: demo-topic
