apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-data-reactive-redis
  labels:
    app: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: spring-data-reactive-redis
          image: acraksghdemo.azurecr.io/redis
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: cloud
            - name: SPRING_DATA_REDIS_HOST
              value: ${{ secrets.REDIS_HOST }}
            - name: SPRING_DATA_REDIS_PASSWORD
              value: ${{ secrets.REDIS_PASSWORD }}
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  labels:
    app: redis
spec:
  ports:
    - port: 8761
      targetPort: 8761
      protocol: TCP
  selector:
    app: redis
  type: LoadBalancer