server:
  port: 8760

spring:
  profiles:
    active: cloud
  cloud:
    azure:
      cosmos:
        database: coffee
        endpoint: https://reactive-spring-demo.documents.azure.com:443/
        key:
        populate-query-metrics: true

redis:
  host: http://localhost:8761