server:
  port: 8760

spring:
  cloud:
    azure:
      cosmos:
        database: coffee
        endpoint: https://reactive-spring-demo.documents.azure.com:443/
        key: xxxxxxxxxxxxxxxxx
        populate-query-metrics: true

redis:
  host: http://localhost:8761

---

spring:
  config:
    activate:
      on-profile: cloud