server:
  port: 8760

spring:
  cloud:
    azure:
      cosmos:
        database: coffee
        endpoint: https://nosql-aks-backend-001.documents.azure.com:443/
        key:
        populate-query-metrics: false

redis:
  host: http://localhost:8761

---

spring:
  config:
    activate:
      on-profile: cloud
  cloud:
    azure:
      cosmos:
        database: coffee
        endpoint: https://nosql-aks-backend-001.documents.azure.com:443/
        key:
        populate-query-metrics: true
redis:
#  host: http://redis-svc.aks-demo.svc.cluster.local:8761
  host: http://redis-svc:8761