apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"redis-enterprise"},"name":"redis-enterprise-operator","namespace":"rec-demo"},"spec":{"replicas":1,"selector":{"matchLabels":{"name":"redis-enterprise-operator"}},"template":{"metadata":{"labels":{"app":"redis-enterprise","name":"redis-enterprise-operator"}},"spec":{"containers":[{"command":["redis-enterprise-operator"],"env":[{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"WATCH_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"OPERATOR_NAME","value":"redis-enterprise-operator"}],"envFrom":[{"configMapRef":{"name":"operator-environment-config","optional":true}}],"image":"redislabs/operator:6.4.2-5","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":8080,"scheme":"HTTP"},"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"name":"redis-enterprise-operator","ports":[{"containerPort":8080}],"resources":{"limits":{"cpu":"4000m","memory":"512Mi"},"requests":{"cpu":"500m","memory":"256Mi"}}},{"command":["/usr/local/bin/admission"],"env":[{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"WATCH_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}}],"envFrom":[{"configMapRef":{"name":"operator-environment-config","optional":true}}],"image":"redislabs/operator:6.4.2-5","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/liveness","port":8443,"scheme":"HTTPS"},"initialDelaySeconds":15,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"name":"admission","ports":[{"containerPort":8443}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":8443,"scheme":"HTTPS"},"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"resources":{"limits":{"cpu":"1000m","memory":"512Mi"},"requests":{"cpu":"250m","memory":"256Mi"}}}],"serviceAccountName":"redis-enterprise-operator"}}}}
  creationTimestamp: "2023-06-11T16:34:32Z"
  generation: 1
  labels:
    app: redis-enterprise
  name: redis-enterprise-operator
  namespace: rec-demo
  resourceVersion: "8245033"
  uid: 93370e37-df2e-41dc-941e-e7bda56fe6d9
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: redis-enterprise-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-enterprise
        name: redis-enterprise-operator
    spec:
      containers:
      - command:
        - redis-enterprise-operator
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: redis-enterprise-operator
        envFrom:
        - configMapRef:
            name: operator-environment-config
            optional: true
        image: redislabs/operator:6.4.2-5
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: redis-enterprise-operator
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: "4"
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - /usr/local/bin/admission
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: operator-environment-config
            optional: true
        image: redislabs/operator:6.4.2-5
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /liveness
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: admission
        ports:
        - containerPort: 8443
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: redis-enterprise-operator
      serviceAccountName: redis-enterprise-operator
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-06-11T16:34:41Z"
    lastUpdateTime: "2023-06-11T16:34:41Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-06-11T16:34:32Z"
    lastUpdateTime: "2023-06-11T16:34:41Z"
    message: ReplicaSet "redis-enterprise-operator-66d5897ff8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
