server:
  port: 8761

spring:
  data:
    redis:
      host: localhost
      port: 6379

---

spring:
  config:
    activate:
      on-profile: cloud
  data:
    redis:
      host: redis-aks-backend-001.redis.cache.windows.net
      port: 6380
      password: 
      ssl: true
      abort-on-connect-fail: false
#      cluster:
#        nodes: x,y,z
#        max-redirects: 2

